[package]
name = "frust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.27", features = ["serde"] }
help = "0.0.0"
itertools = "0.11.0"
rand = "0.8.5"
threadpool = "1.8.1"
